apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeasy-deployment
  labels:
    app: yeasy
    chaos: enabled
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yeasy
  template:
    metadata:
      labels:
        app: yeasy
        chaos: enabled
    spec:
      containers:
      - name: yeasy
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: yeasy
  labels:
    app: yeasy
    service: yeasy
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: yeasy 