apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
    kube-monkey/enabled: enabled
    kube-monkey/identifier: apache-deployment
    kube-monkey/mtbf: '1'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: '1'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        kube-monkey/enabled: enabled
        kube-monkey/identifier: apache-deployment
        kube-monkey/mtbf: '1'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
    spec:
      containers:
      - name: apache
        image: httpd:2.4.62
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
    service: apache
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: apache