apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
    chaos: enabled
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        chaos: enabled
    spec:
      containers:
      - name: apache
        image: httpd:2.4.62
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
    service: apache
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: apache